### ISSUE TITLE
how to customize server url

### ISSUE THREAD

**Issue by rowrowrowrow** [Trulioo/trulioo-embedid-client#12]
Is it possible/do you have a recommended way to use the TruliooClient and customize the server url as if we were directly using EmbedId?

**Comment by mkotsollaris** [comment]
Could you please provide some more details regarding your objective?

**Comment by rowrowrowrow** [comment]
Yep. We would like to route EmbedId requests through our own server in order to capture verified field data, and control which users may access the Identity Verification process (i.e. add some metadata from the front-end to each request to identify the current user).

**Comment by mkotsollaris** [comment]
> EmbedId requests through our own server in order to capture verified field data

The way EmbedID works is that by the end of your EmbedID experience, it will provide you an `experienceTransactionId` which you can use to get some metadata. Here's some documentation that might help you out with that. In a way, you route through your backend server to retrieve experience details. See [documentation](https://gateway-admin.trulioo.com/documentation/embedid) for more.

If you want to add/remove extra fields and other information, all you have to do is go to [EmbedID ](https://gateway-admin.trulioo.com/manager) and select which fields do you want and which not.

Does that help?

**Comment by rowrowrowrow** [comment]
Yes the information helps, thanks! I have some follow on questions though. 

- Do the /experienceTransaction/{experienceTransactionId} and /experienceTransaction/{experienceTransactionId}/detailedResult endpoints return the complete data submitted or partial/scrubbed? If partial/scrubbed is there a resource I can review what data is omitted or modified?

- Are we able to control how many times they attempt to submit? i.e. impose some sort of rate limit for each accessToken.

**Comment by mkotsollaris** [comment]
> Do the /experienceTransaction/{experienceTransactionId} and /experienceTransaction/{experienceTransactionId}/detailedResult endpoints return the complete data submitted or partial/scrubbed? If partial/scrubbed is there a resource I can review what data will be omitted or modified?

Absolutely, you have full control and full visibility on the data that was submitted and on the status (Match or NoMatch).

>Are we able to control how many times they attempt to submit? i.e. impose some sort of rate limit for each accessToken.

Yes, Access Token creation has to occur through your Backend-channel communication. For instance, a strategy could be to issue X amount of access tokens per user. You fully control this logic. As long as EmbedID has a valid access token (which you decide when to issue and to whom) EmbedID will render accordingly.

**Comment by mkotsollaris** [comment]
You can go to [Manager](https://gateway-admin.trulioo.com/author) -> EmbedID and for an IDV-only experience, you can click on "Save and Preview". This is a great tool which demonstrates everything you get from EmbedID:

![image](https://user-images.githubusercontent.com/8595514/85466180-7ef8a880-b55e-11ea-9ea9-1253ed9aba17.png)

**Comment by rowrowrowrow** [comment]
Thanks, is there a way to invalidate an access token?

**Comment by mkotsollaris** [comment]
Access Tokens are always created with a short TTL and immediately invalidated after a transaction takes place. Would that help your use case?

**Comment by rowrowrowrow** [comment]
Yep, it sounds like that can work with our use case but I'm not seeing this behavior using the trial keys (I'm guessing this is intentional). 

In production, once a transaction is complete, fail or success, the access token that is used to load the iframe will be invalidated but the iframe has already been loaded. So what should I expect for the UX post-submission? Do we need to handle the entire post submission UX via the handleResponse on our end or will the form display some kind of post-submit notice itself?

**Comment by mkotsollaris** [comment]
You got it right. You will have to handle this behavior through `handleResponse`. This function will spit the experienceTransactionId and thereafter you control what happens to your DOM.

Regarding the post-submit notice, you also control that. We do have plans in the near future to have an implementation of a final view, say 'Congratulations, you completed your onboarding.', but nothing as of now. 

Please let me know if you would like to see that feature and we would do our best to prioritize accordingly.

**Comment by mkotsollaris** [comment]
trial and live normal access tokens get invalidated after all verifications are run for the experience. Only preview access tokens are able to be used multiple times for demonstration purposes.

**Comment by rowrowrowrow** [comment]
Thanks for your help so far!

Can you please provide an example and all details for how to do both of the following requests:

/experienceTransaction/{experienceTransactionId}

/experienceTransaction/{experienceTransactionId}/detailedResult

**Comment by mkotsollaris** [comment]
By the end of your experience (either Identity verification or document verification or both), EmbedID will return an `experienceTransactionId` in from `handleResponse`. If you pass that in `experienceTransaction`, you will be able to see the result of the payload.

Let me know if that helps.

**Comment by rowrowrowrow** [comment]
We are, but still running into errors even while using the requests during the 'Preview' provided by trulioo as examples to base our own requests on. 

Can you provide a detailed example of all the required headers, params, query params, endpoints, anything else to recreate the request?

**Comment by mkotsollaris** [comment]
in the headers, all you have to do is have `x-trulioo-api-key` header, although if you are using the [nodejs middleware](https://github.com/Trulioo/trulioo-embedid-middleware) for access token generation, you shouldn't need to add any custom headers as it does it for you.

If that doesn't work, please [schedule a call ](https://www.trulioo.com/company/contact-us/) with our support team and we will try to drill down to your use case.

**Comment by rowrowrowrow** [comment]
We followed the middleware exactly as an example, among other things, and it just didn't work. So we'll schedule a call. 

I was hoping you could confirm the exact full url, headers, body, etc. to perform the request from any environment.

**Comment by mkotsollaris** [comment]
Here's an example of my local integration, which as you can see I am able to render EmbedID:
![image](https://user-images.githubusercontent.com/8595514/86384612-d7f1cc00-bc43-11ea-9d38-286fb9ea77a5.png)

After submition, `handleResponse` reports `7aed93b5e8eb4fcca58c2e54ac78b0dc` as experienceTransactionId, here's my postmanCall:

>curl -X GET \
  https://gateway.trulioo.com/experienceTransaction/7aed93b5e8eb4fcca58c2e54ac78b0dc/detailedResult \
  -H 'cache-control: no-cache' \
  -H 'x-trulioo-api-key: ,MY_API_KEY_HERE'

![image](https://user-images.githubusercontent.com/8595514/86386136-3b7cf900-bc46-11ea-88f8-3296ed042f48.png)

Are you sure you are using https://gateway.trulioo.com as your base URL, with the right `x-trulioo-api-key` header?

**Comment by rowrowrowrow** [comment]
Thanks for the example! 

So the issue for us was the base URL. Both the base URL in the middleware ('https://api-gateway-admin.trulioo.com') and the one used in the preview ('https://embedid.trulioo.com') for making this request are different than the one above.

Could you explain the difference between transactionID, transactionRecordId and experienceTransactionId ?

Also, are these verification requests observable in Global Gateway?

**Comment by mkotsollaris** [comment]
That's a good note. You shouldn't really need to worry about GlobalGateway correlation, this is independent of your integration. The only variable that you will need while using EmbedID is `experienceTransactionId` which is generated after the end of the transactions.

Currently, the team is working on providing better documentation and we will take your feedback into consideration to update it.
